### ISSUE TITLE
Avoid "antenna ID" nomenclature

### ISSUE THREAD

**Issue by david-macmahon** [realtimeradio/ata_snap#12]
The firmware and the control software make reference assigning an "antenna ID" to the SNAP.  This field is used to identify and differentiate amongst different SNAPs when processing packets from more than one SNAP.  It is an important field, but it should be called "F engine ID" (aka "FID") rather than "antenna ID".  "F engine ID" is a much more appropriate name for this field since it will be used by downstream software to collate packets from different F engines.  These packets will contain data from antennas, but which specific antennas are being used is not important at this level.  In fact, it is possible to connect one polarization from two different antennas to a SNAP board, so the concept of a singular "antenna ID" isn't fitting for that case (nor would be creating two "antpol ID" fields).  The software receiving the packets will ultimately need to know which antpols are connected to which SNAP inputs, but that can be handled better at the software level.  That info need not creep down into the gateware's awareness.

**Comment by realtimeradio** [comment]
Agreed. Terminology / register names changed in rev 2 onwards
