### ISSUE TITLE
Use SNAP board's 1pps rather than ADC's

### ISSUE THREAD

**Issue by wfarah** [realtimeradio/ata_snap#15]
As already noticed before, the ADC 1pps is dropping pulses. We changed the wiring such that we use the 1pps directly to the SNAP board, and it seems that it is working as expected with no pulses seen to be dropping.

A change of value to the `sync_sel` register must be performed somewhere to reflect this change and make it a default. We wired all the 1pps here accordingly

**Comment by realtimeradio** [comment]
Do you want this to be --
- A config file parameter?
- An initialization script command line parameter?
- fixed so you never have to think about it?

**Comment by wfarah** [comment]
Fixed. Until we find a critical flaw in using the connection

**Comment by realtimeradio** [comment]
Should now be fixed in 
fee15a2

**Comment by wfarah** [comment]
A tiny bug in:

https://github.com/realtimeradio/ata_snap/blob/11c34b25ceb1ea36d18c681b723524102bdb86fe/sw/ata_snap/src/ata_snap_fengine.py#L141

`_` in `_pps_source` needs to be removed
