### ISSUE TITLE
Tiny bug in snap_feng_init.py

### ISSUE THREAD

**Issue by wfarah** [realtimeradio/ata_snap#16]
In:

https://github.com/realtimeradio/ata_snap/blob/nov-observing/sw/ata_snap/src/ata_snap_fengine.py#L144

`self.write_int("corr_feng_id", self.feng_id)` -> `self.fpga.write_int("corr_feng_id", self.feng_id)`

**Comment by wfarah** [comment]
Should be solved in the latest pull request

**Comment by realtimeradio** [comment]
Thanks!
