### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by wfarah** [realtimeradio/ata_snap#2]
There's a small typo in the documentation in page 3 in the voltage mode packet desription block:
`int32` -> `int4`, `spectrometer_packet` -> `voltage_packet`

**Comment by realtimeradio** [comment]
Thanks @wfarah -- can you confirm that https://github.com/realtimeradio/ata_snap/blob/voltage-capture/docs/build/latex/atasnapfirmwaremanual.pdf corrects the errors you found, then I'll close this.

**Comment by wfarah** [comment]
Yes, it seems fine to me! Thanks Jack
