### ISSUE TITLE
Add programmable coarse (ADC sample) delay block

### ISSUE THREAD

**Issue by david-macmahon** [realtimeradio/ata_snap#9]
A user programmable coarse delay (i.e. with granularity of 1 ADC sample) would be useful for compensating for the different cable length delays from the antennas.  A max delay of 4096 samples would allow for a maximum of approximately 4 microseconds of delay (more than adequate).  A max delay of 2048 samples would allow for a maximum delay of approximately 2 microseconds.  I don't know when the fiber lengths were last measured (via OTDR) or what the measurements show, but anecdotally the differences have been reported to span 1500 ns.  The 2048 sample delay depth would not leave much headroom so the 4096 depth would be preferable.  Deeper delay buffers would probably not be necessary, but if the FPGA has BRAM to spare then a deeper buffer wouldn't be a bad thing.

**Comment by realtimeradio** [comment]
16k samples of delay available from firmware rev2
